### ISSUE TITLE
[BUG] TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by Dlg15** [shd101wyy/vscode-markdown-preview-enhanced#1853] opened 2023-10-22 05:15 UTC
**Describe the bug**
After installing the plugin, the following error appears:
> TypeError: Converting circular structure to JSON --> starting at object with constructor 'Object' | property '\df@tag' -> object with constructor 'Object' | property 'tokens' -> object with constructor 'Array' | ... | property 'settings' -> object with constructor 'zN' --- property 'macros' closes the circle

**Environment**
- OS: Windows 10
- VSCode: 1.82.0
- Markdown Preview Enhanced: 0.8.8

**To Reproduce**

**Expected behavior**

**Markdown file**
Please attach the markdown file that can reproduce the bug.

**Screenshots**

**Additional context**

**Comment by Kariiboo** [comment] 2023-10-22 07:34
Hello. I have the same problem. It seems to be linked to the use of `\nonumber` in a math expression in a .md file.

Here after some details to reproduce :

- From an empty .md file, open preview to the side.
- Add in a ````math ` section

> ```math
> \begin{align} \nonumber
>   A = B + C
> \end{align}
> ```

The rendering is OK
- Save the file.
- Close VSCode
- Open VSCode, open the .md file.
- open preview to the side. I have the error message.
`TypeError: Converting circular structure to JSON --> starting at object with constructor 'Object' | property '\@eqnsw' -> object with constructor 'Object' | property 'tokens' -> object with constructor 'Array' | ... | property 'settings' -> object with constructor 'zN' --- property 'macros' closes the circle`

**Comment by shd101wyy** [comment] 2023-10-22 14:02
Hi there. Are you using KaTeX or MathJax for rendering the math?

**Comment by Kariiboo** [comment] 2023-10-22 14:27
Hi !
I use KaTex.
![image](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/10746887/b5e04b87-a0eb-4199-a484-74179181eece)

When I switch for MathJax, the rendering is OK.

**Comment by shd101wyy** [comment] 2023-10-23 00:43
Thanks for the details. I will look into the katex issue.

**Comment by shd101wyy** [comment] 2023-10-23 02:34
Okay this bug should be fixed now in `0.8.9`. Thanks

**Closed by shd101wyy** 2023-10-23 02:34 UTC
Labels: bug
